name: Deploy to ECR

on:
  push:
    branches:
      - main

env:
  working-directory: ./backend
  ecr-repository: 471112874945.dkr.ecr.eu-central-1.amazonaws.com/syncmeet
  aws-region: eu-central-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image to Amazon ECR
        working-directory: ./backend
        run: |
          ECR_REGISTRY=471112874945.dkr.ecr.eu-central-1.amazonaws.com
          ECR_REPOSITORY=syncmeet
          IMAGE_TAG=latest
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
  deploy:
    needs: build-and-push
    runs-on: [ self-hosted ]

    steps:
      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Image from AWS ECR
        run: docker pull 471112874945.dkr.ecr.eu-central-1.amazonaws.com/syncmeet:latest

      - name: Delete old container
        run: docker rm -f syncmeet

      - name: Run docker container
        run: docker run --env-file env.list -d -p 443:8080 --restart on-failure --name syncmeet 471112874945.dkr.ecr.eu-central-1.amazonaws.com/syncmeet:latest
