name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          cd ./frontend
          npm install
      - name: Build
        run: |
         cd ./frontend
         npm run dist
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        run: |
          ls
          cd ./frontend
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
